# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.",
#         "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [
{"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy", "question": "A group of islands is called an &#039;archipelago&#039;.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy", "question": "The Spitfire originated from a racing plane.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium", "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy", "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium", "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Art", "type": "boolean", "difficulty": "medium", "question": "Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard", "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "medium", "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard", "question": "&quot;Cube&quot;, &quot;Cube 2: Hypercube&quot; and &quot;Cube Zero&quot; were directed by the same person.", "correct_answer": "False", "incorrect_answers": ["True"]}, {
    "category": "Science: Computers", "type": "boolean", "difficulty": "easy", "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy", "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Cats have whiskers under their legs.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy", "question": "Actor Tommy Chong served prison time.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "You can square root a negative number with an imaginary number &quot;i&quot;.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium", "question": "In &quot;Avatar: The Last Airbender&quot; and &quot;The Legend of Korra&quot;, Lavabending is a specialized bending technique of Firebending.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium", "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium", "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.", "correct_answer": "False", "incorrect_answers": ["True"]}]
